### ISSUE TITLE
[New Player] Scale width of player with width of window

### ISSUE THREAD

**Issue by fvlvte** [fvlvte/knurclub-frontend-public#1]
**SCOPE**
We need to scale size of new player `/new/player` with width of the browser window.
The minimal width to handle is `800px`, scale rest of elements based on window width.

**DESIGN**
https://www.figma.com/file/M3TLZ6TWqQcaY0CHH8JCK8/Knur-Club?type=design&node-id=2743-529&mode=design&t=ApA7lcxGaY2wsoBt-4

**ACCEPTANCE CRITERIA**
- Player is responsive respecting minimal width of 800px.
- Height should be respected to aspect ratio of the design.

**Comment by M-Itrych** [comment]
Nie mam możliwości przypiąć pull requesta
